# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZNUgckXVXlpAMyBgFYf00pqHNpYgydEW
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import io
from openpyxl import Workbook
from openpyxl.drawing.image import Image as XLImage
import tempfile
import os

st.set_page_config(layout="wide")
st.title("🧪 Stability Study Report Generator")

# --- HEADER INPUTS ---
batch_number = st.text_input("Batch Number")
packaging_mode = st.text_input("Packaging Mode")

st.markdown("### ➕ Add Stability Condition Data")

conditions = st.multiselect(
    "Select Stability Conditions:",
    ["25C_60RH", "30C_65RH", "40C_75RH"],
    default=["40C_75RH"]
)

# --- Timepoints ---
available_timepoints = ["Initial", "1M", "3M", "6M", "9M", "12M", "18M", "24M"]
selected_timepoints = st.multiselect("Select Timepoints to Include:", available_timepoints, default=available_timepoints)

# --- Manual Input Table for Each Condition ---
all_data = {}
chart_paths = []

# Utility function to extract numbers
def get_numeric(value):
    try:
        return float(''.join([s for s in value if s.isdigit() or s == '.']))
    except:
        return None

# Temporary directory for chart images
temp_dir = tempfile.mkdtemp()

for condition in conditions:
    st.markdown(f"### 📋 Data for {condition}")
    param_names = ["Assay", "Dissolution", "Unknown Impurity", "Total Impurity"]
    n_params = st.number_input(f"Number of Parameters for {condition}", min_value=1, max_value=20, value=len(param_names), key=f"np_{condition}")

    data = []
    for i in range(n_params):
        cols = st.columns(len(selected_timepoints) + 2)
        pname = cols[0].text_input("Parameter", value=param_names[i] if i < len(param_names) else f"Param {i+1}", key=f"p_{condition}_{i}")
        spec = cols[1].text_input("Specification", value="", key=f"s_{condition}_{i}")
        row = [pname, spec]
        for j, tp in enumerate(selected_timepoints):
            val = cols[j+2].number_input(tp, value=np.nan, format="%.4f", key=f"val_{condition}_{i}_{tp}")
            row.append(val)
        data.append(row)

    columns = ["Parameter", "Specification"] + selected_timepoints
    df = pd.DataFrame(data, columns=columns)
    all_data[condition] = df
    st.dataframe(df)

    # --- Generate and Save Charts ---
    for _, row in df.iterrows():
        pname = row["Parameter"]
        values = row[selected_timepoints].astype(float)
        if values.count() >= 2:
            times_numeric = np.array([i for i, val in enumerate(values) if not np.isnan(val)]).reshape(-1, 1)
            values_clean = np.array([val for val in values if not np.isnan(val)])
            model = LinearRegression().fit(times_numeric, values_clean)
            pred = model.predict(times_numeric)

            fig, ax = plt.subplots(figsize=(6, 3))
            ax.plot(selected_timepoints, row[selected_timepoints], marker='o', label='Observed')
            ax.plot(np.array(selected_timepoints)[~np.isnan(values)], pred, '--', label='Trendline', color='gray')

            spec_text = row['Specification']
            if pname.lower() == 'assay':
                try:
                    limits = [float(s) for s in spec_text.replace('%','').split('-')]
                    ax.axhline(limits[0], color='red', linestyle='--', label='Lower Spec')
                    ax.axhline(limits[1], color='red', linestyle='--', label='Upper Spec')
                except: pass
            elif pname.lower() == 'dissolution':
                try:
                    limit = get_numeric(spec_text)
                    if limit: ax.axhline(limit, color='orange', linestyle='--', label='NLT Spec')
                except: pass
            elif 'impurity' in pname.lower():
                try:
                    limit = get_numeric(spec_text)
                    if limit: ax.axhline(limit, color='purple', linestyle='--', label='NMT Spec')
                except: pass

            ax.set_title(f"{pname} - {condition}")
            ax.set_ylabel("Value")
            ax.set_xlabel("Time Point")
            ax.grid(True)
            ax.legend()
            st.pyplot(fig)

            # Save chart to PNG
            chart_path = os.path.join(temp_dir, f"{condition}_{pname}.png")
            fig.savefig(chart_path)
            chart_paths.append((condition, pname, chart_path))

# === Create Excel with Tables and Charts ===
if st.button("📥 Download Full Excel Report"):
    excel_output = io.BytesIO()
    wb = Workbook()
    wb.remove(wb.active)

    for condition, df in all_data.items():
        ws = wb.create_sheet(title=condition)
        ws.append([f"Batch Number: {batch_number}", f"Packaging Mode: {packaging_mode}"])
        ws.append([])
        ws.append(list(df.columns))
        for row in df.itertuples(index=False):
            ws.append(list(row))

        # Insert charts
        for cond, pname, img_path in chart_paths:
            if cond == condition:
                ws.append([])
                ws.append([f"Chart for {pname}"])
                img = XLImage(img_path)
                img.width = 500
                img.height = 300
                ws.add_image(img, f"A{ws.max_row + 1}")

    wb.save(excel_output)
    st.download_button(
        label="📥 Download Excel with Data and Charts",
        data=excel_output.getvalue(),
        file_name=f"Stability_Study_Report_{batch_number}.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

# Footer
st.markdown("---")
st.markdown("Built for Stability Analysis | Pharma Quality Tools")")